Added ImageCompression Augmentation Function
datature/discolight pull request #10
Opened 2020-08-06 09:24 UTC by denzel-datature

Main changes added:

- Added imagecompression.py under src/discolight/augmentations/

2020-08-07 08:21 UTC, ian-datature requested changes

2020-08-07 08:21 UTC, ian-datature commented on src/discolight/augmentations/imagecompression.py
> +    """Image compress the given image.
```suggestion
    """Apply a compression effect to the given image.
```

2020-08-07 08:21 UTC, ian-datature commented on src/discolight/augmentations/imagecompression.py
> +    Works for both jpeg/jpg and png format.
Not sure if this line is necessary. All augmentations should work for any image that can be loaded with OpenCV.

2020-08-07 08:21 UTC, ian-datature commented on src/discolight/augmentations/imagecompression.py
> +        """Construct a Image compression augmentation.
```suggestion
        """Construct a ImageCompression augmentation.
```

2020-08-07 08:21 UTC, ian-datature commented on src/discolight/augmentations/imagecompression.py
> +            "Compression strength between 0 to 100",
```suggestion
            "Compression strength",
```
Using the `BoundedNumber` type will cause information about the  bound to automatically appear in the documentation, so you don't need to add it to the param description.

2020-08-07 08:50 UTC, ian-datature approved these changes

2020-08-10 10:52 UTC, gkeechin approved these changes

2020-08-11 07:27 UTC, merged