Add ColorTemperature augmentation
datature/discolight pull request #2
Opened 2020-07-29 11:38 UTC by r-k-jonynas

2020-07-30 06:43 UTC, ian-datature requested changes
Please fix the docstring style errors as reported by the linter and we should be go to go. Thanks!

2020-07-30 06:43 UTC, ian-datature commented on tests/augmentations/test_color_temperature.py
> +    ), "Performing augmentation does not yield original augmentation"
The assert message should state that you are checking the bounding boxes
```suggestion
    ), "Performing augmentation does not yield original bounding boxes"
```

2020-07-30 06:43 UTC, ian-datature commented on tests/augmentations/test_color_temperature.py
> +    ), "Performing augmentation does not yield original augmentation"
Same as line 30

2020-08-03 04:11 UTC, ian-datature approved these changes

2020-08-05 09:54 UTC, gkeechin approved these changes
lgtm

2020-08-05 09:54 UTC, merged