Motionblur PR without testing
datature/discolight pull request #4
Opened 2020-08-03 07:13 UTC by arunraja-hub

This PR has not been tested as there is some issue with testing on Windows

2020-08-05 07:26 UTC, arunraja-hub commented
`AssertionError: Bounding boxes for motionblur do not match` despite making no changes to bbox
Possible issue with snapshots, @ian-datature will look into this

2020-08-06 04:00 UTC, ian-datature requested changes
I've made a few comments / suggestions. I also fixed the snapshots issue in #6. When this is merged you should pull from `master`,  regenerate the snapshots, and push the updated snapshot files as a commit to this pull request. Thanks!

2020-08-06 04:00 UTC, ian-datature commented on src/discolight/augmentations/motionblur.py
> +class motionblur(Augmentation):
Class names should start with a capital letter and be in camel case (e.g., `MotionBlur`)

2020-08-06 04:00 UTC, ian-datature commented on src/discolight/augmentations/motionblur.py
> +    """Add motionblur to a given image."""
```suggestion
    """Add motion blur to a given image."""
```

2020-08-06 04:00 UTC, ian-datature commented on src/discolight/augmentations/motionblur.py
> +        return Params().add(
Please pull the latest changes from `master` and update the `Params` accordingly. If there is a limit on the `kernel_size` you should use a `BoundedNumber` type. The `direction` parameter should probably be an enum. You can see in the README how to define and use these types.

2020-08-07 06:24 UTC, ian-datature approved these changes

2020-08-10 10:52 UTC, gkeechin approved these changes

2020-08-17 09:12 UTC, merged